### ISSUE TITLE
Map freezes after choosing to add Overview from "Tools and Behavior" panel 

### ISSUE THREAD

**Issue by alex-lindeman** [nationalparkservice/npmap-builder#229] opened 2015-08-13 15:33 UTC
mapId=b4deeabb-8e03-478f-b9ec-4cd2b53ec0ba

When I'm in the Tools and Behavior screen and choose to add an Overview to my map, the map frame tries to reload the map - but it never finishes reloading. If I uncheck Overview, the map reloads just fine.

**Comment by nateirwin** [comment] 2015-08-13 22:10
Hi @alex-lindeman, I can't seem to reproduce this issue in Chrome. Which browser are you using?

**Comment by alex-lindeman** [comment] 2015-08-13 22:12
Oh, sorry for not reporting that; Firefox 38 ESR.

On Thu, Aug 13, 2015 at 2:10 PM, Nate Irwin <notifications@github.com>
wrote:

> Hi @alex-lindeman <https://github.com/alex-lindeman>, I can't seem to
> reproduce this issue in Chrome. Which browser are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/229#issuecomment-130863254>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment] 2015-08-13 22:16
Interesting, it's working in Firefox for me too. Maybe a cache issue? Before you clear the cache, though, can you right-click on the page in Builder, select "Inspect Element", click "Console" in the developer tools that popup, then check/uncheck the overview button? I'd like to know if you see an error popup in the console.

**Comment by alex-lindeman** [comment] 2015-08-13 22:18
TypeError: L.npmap.layer[a.layer.type] is not a function

On Thu, Aug 13, 2015 at 2:16 PM, Nate Irwin <notifications@github.com>
wrote:

> Interesting, it's working in Firefox for me too. Maybe a cache issue?
> Before you clear the cache, though, can you right-click on the page in
> Builder, select "Inspect Element", click "Console" in the developer tools
> that popup, then check/uncheck the overview button? I'd like to know if you
> see an error popup in the console.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/229#issuecomment-130864167>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by alex-lindeman** [comment] 2015-08-13 22:18
Oh, also an alert:

This site makes use of a SHA-1 Certificate; it's recommended you use
certificates with signature algorithms that use hash functions stronger
than SHA-1.[Learn More]

On Thu, Aug 13, 2015 at 2:17 PM, Lindeman, Alex <alex_lindeman@nps.gov>
wrote:

> TypeError: L.npmap.layer[a.layer.type] is not a function
>
> On Thu, Aug 13, 2015 at 2:16 PM, Nate Irwin <notifications@github.com>
> wrote:
>
>> Interesting, it's working in Firefox for me too. Maybe a cache issue?
>> Before you clear the cache, though, can you right-click on the page in
>> Builder, select "Inspect Element", click "Console" in the developer tools
>> that popup, then check/uncheck the overview button? I'd like to know if you
>> see an error popup in the console.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nationalparkservice/npmap-builder/issues/229#issuecomment-130864167>
>> .
>>
>
>
>
> --
>
> Alex Lindeman
>
> Visual Information Specialist / Alaska Region Web Coordinator
> Denali National Park and Preserve
> (907) 683-6392 (o)
> (907) 378-0366 (c)
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment] 2015-08-13 22:23
Definitely looks like a caching issue. Can you try clearing your cache?

**Comment by alex-lindeman** [comment] 2015-08-13 22:35
No joy. I logged out of insidemaps.nps.gov, cleared cache, cleared cookies,
restarted Firefox, and still I get the same message.

On Thu, Aug 13, 2015 at 2:23 PM, Nate Irwin <notifications@github.com>
wrote:

> Definitely looks like a caching issue. Can you try clearing your cache?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/229#issuecomment-130865397>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment] 2015-08-13 22:35
Ok, let's try this: Can you send me the map id of the map you're working on?

**Comment by alex-lindeman** [comment] 2015-08-13 22:41
b4deeabb-8e03-478f-b9ec-4cd2b53ec0ba

On Thu, Aug 13, 2015 at 2:36 PM, Nate Irwin <notifications@github.com>
wrote:

> Ok, let's try this: Can you send me the map id of the map you're working
> on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-builder/issues/229#issuecomment-130868255>
> .
>



-- 

Alex Lindeman

Visual Information Specialist / Alaska Region Web Coordinator
Denali National Park and Preserve
(907) 683-6392 (o)
(907) 378-0366 (c)

**Comment by nateirwin** [comment] 2015-08-13 23:04
Great, I see the error. I'll get right on this.

**Comment by nateirwin** [comment] 2015-08-13 23:27
This is fixed now. Sorry about the problem!

**Closed by nateirwin** 2015-08-13 23:27 UTC
Labels: bug
