### ISSUE TITLE
Cannot Delete maps on Builder Dashboard

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/npmap-builder#217] opened 2015-06-09 16:55 UTC
Uncaught TypeError: Cannot set property 'innerHTML' of null  app.js:117 
Uncaught TypeError: Cannot read property 'modal' of undefined app.js:11

**Comment by nateirwin** [comment] 2015-08-06 16:30
Can't reproduce. Closing as I think this was a local cache issue.

**Closed by nateirwin** 2015-08-06 16:30 UTC
Labels: bug
