### ISSUE TITLE
Issue using Places overlay

### ISSUE THREAD

**Issue by alex-lindeman** [nationalparkservice/npmap-builder#234] opened 2015-09-16 17:01 UTC
In firefox, when I try to add the DENA Trails overlay to a map, I can't close the Add Overlay menu - I can click the save button but it just goes grayish and doesn't actually dismiss the menu.

In Chrome, I've tried adding the same task. However, once I open the Add Overlay menu, and click on Places, I can only select the layer (Trails) - the park pick list is empty for some reason. 

Let me know if that's too vague, I can attach screenshots if desired

**Comment by nateirwin** [comment] 2015-10-22 17:45
I'm having a hard time reproducing this one, as well. I just added DENA trails using Chrome, Safari, and Firefox successfully. Can you try again?

**Comment by nateirwin** [comment] 2015-10-27 17:00
Closing for now, as I can't reproduce. Feel free to open again, @alex-lindeman if you see this again.

**Closed by nateirwin** 2015-10-27 17:00 UTC
Labels: bug
